apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command:
              - /usr/sbin/nginx
              - -s
              - quit
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 443
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 443
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 1
        resources:
          requests:
            cpu: 10m
            memory: 30Mi
