apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  clusterIP: 
  loadBalancerIP: 
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  # deployment
  externalTrafficPolicy: Cluster
  # daemonset
  #externalTrafficPolicy: Local
