apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
  clusterIP:
  loadBalancerIP:
  loadBalancerSourceRanges:
  - 59.126.155.55/32
  externalTrafficPolicy: Local
