apiVersion: v1
kind: Service
metadata:
  name: envoy-cluster-ip
spec:
  type: ClusterIP
  clusterIP:
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 10443
    protocol: TCP
  - name: admin-http
    port: 9901
    targetPort: 9901
    protocol: TCP
