apiVersion: v1
kind: Service
metadata:
  name: envoy-cluster-ip
spec:
  type: ClusterIP
  clusterIP:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
